[user]
name = "Colin Chan"
email = "colin+git@lumeh.org"

[ui]
default-command = "log"
diff-formatter = ":git"
pager = "less"

[colors]
"diff added" = { fg = "green" }
"diff token" = { underline = false }
"diff removed" = { fg = "red" }
"line_number" = { fg = "black" }

[remotes.origin]
auto-track-bookmarks = "colin/*"
