[user]
name = "Colin Chan"
email = "colin@pylonlending.com"

[ui]
default-command = "log"
diff-formatter = ":git"
pager = "less"

[colors]
"diff added" = { fg = "green" }
"diff token" = { underline = false }
"diff removed" = { fg = "red" }
"line_number" = { fg = "black" }

[remotes.origin]
auto-track-bookmarks = "colin/*"

[templates]
file_annotate = "join(' ', commit.commit_id().short(8), pad_start(12, truncate_end(12, commit.author().timestamp().ago())), pad_start(9, truncate_end(9, commit.author().name())), pad_start(3, line_number), content)"

[template-aliases]
"format_short_signature(signature)" = "signature.name()"
